# Generated by Django 5.2.15 on 2026-08-16 15:03

import django.db.models.deletion
from django.db import migrations, models


def link_candidates(apps, schema_editor):
    Candidate = apps.get_model('invites', 'Candidate')
    SurveyResponse = apps.get_model('traits', 'SurveyResponse')
    for response in SurveyResponse.objects.filter(candidate__isnull=True).iterator():
        candidate = Candidate.objects.filter(email=response.respondent_email).order_by('-created_at', '-pk').first()
        if candidate:
            response.candidate_id = candidate.pk
            response.save(update_fields=['candidate'])


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='invites.candidate'),
        ),
        migrations.RunPython(link_candidates, migrations.RunPython.noop),
    ]
