"""Text-observation simulations, isolated from candidate models and sessions.

These are synthetic decision tests, not browser/perceptual benchmarks. Timing
is generated by the model; it must never be reported as human reaction time.
"""
import math
import random
import uuid
from statistics import mean

from games.catalog import GAMES
from games.views import EXPEDITION_BASE_DECKS, EXPEDITION_REVERSAL_INDEX, EXPEDITION_REVERSAL_MAP, EXPEDITION_TRIALS
from traits.survey_definition import QUESTION_TEXT, response_quality, score_answers

from .simulation_llm import SimulationError, decide


PERSONAS = {
    'balanced': ('균형형', '신중히 읽되 과도하게 완벽을 추구하지 않는다. 모르는 것은 탐색하고 피드백으로 판단을 수정한다.'),
    'careful': ('신중형', '결정 전에 확인하는 편이다. 시간이 더 걸리고 불확실한 선택과 손실을 꺼린다. 갑작스러운 변화에는 잠시 주저한다.'),
    'hasty': ('서두름형', '빠르게 결정하며 세부사항을 가끔 놓친다. 즉각적 보상에 끌리고 뒤늦게 실수를 알아차리기도 한다.'),
    'impression': ('좋은 인상 응답형', '성향 문항에서 좋은 인상을 주려고 답한다. 실제 과제에서는 보통의 주의력과 판단력을 가진 사람처럼 행동한다.'),
}
TASKS = {'traits': '성향파악', **{g['slug']: g['title'] for g in GAMES if g['implemented']}}
# ponytail: text-task lengths mirror templates; if game protocols change,
# revise these scenarios too. They do not replace the browser game engines.
LENGTHS = {
    'traits': len(QUESTION_TEXT), 'radar-control': 70, 'emergency-brake': 70,
    'sorting-center': 70, 'space-station-schedule': 127, 'drone-tracking': 12,
    'quality-inspector': 50, 'cipher-lab': 15, 'flash-comm': 24,
    'expedition-investment': EXPEDITION_TRIALS,
}
RULES = {
    'traits': '평소 자신의 모습과 일치하는 정도를 1~5로 답하세요. 1=전혀 그렇지 않다, 5=매우 그렇다. 무응답은 null.',
    'radar-control': '초록 일반 비행체에는 space, 빨강 위험 비행체에는 null(기다림).',
    'emergency-brake': '초록 상자에 space로 반응하되 빨강 정지 신호가 나오면 멈추세요. null=반응 억제. 시간 순서로 기술된 상황입니다.',
    'sorting-center': '현재 기준에 따라 분류: 색상은 파랑=left, 노랑=right; 모양은 원=left, 네모=right.',
    'space-station-schedule': '홀수=left, 짝수=right, 별= p. 시작 후 80초·160초 각각 15초 안에 p를 한 번 눌러 약속을 수행하세요. 행동 배열로 답하세요. 가상 시계가 표시됩니다.',
    'drone-tracking': '처음 표시된 표적들을 좌표 프레임에서 추적하고, 마지막 프레임에서 해당 표적의 번호(0부터)를 배열로 선택하세요. 번호는 매 프레임 위치순으로 재부여됩니다.',
    'quality-inspector': '노란 회전 부품이 하나라도 있으면 f, 모두 파란 정상 부품이면 j.',
    'cipher-lab': '앞의 기호 상태 3개에서 규칙을 추론하고 네 번째 상태의 보기 번호(0~3)를 선택하세요.',
    'flash-comm': '연속 신호에서 색깔 원의 색과 검은 도형의 모양을 기억하세요. [blue/orange, circle/square] 배열로 답하세요.',
    'expedition-investment': 'A/B/C/D 중 탐사 지역 하나를 선택하세요. 결과를 보고 자원을 늘리도록 판단하세요. 지역별 확률은 알려져 있지 않습니다.',
}


def new_run(model, persona, task, mode, seed, user_id):
    tasks = list(TASKS) if task == 'all' else [task]
    return {
        'version': 1, 'id': uuid.uuid4().hex, 'user_id': user_id, 'model': model,
        'persona': persona, 'seed': seed, 'mode': mode, 'tasks': tasks,
        'limits': {t: LENGTHS[t] if mode == 'full' else min(5, LENGTHS[t]) for t in tasks},
        'task_index': 0, 'records': [], 'completed': [], 'adaptive': {},
    }


def observation(state):
    task = state['tasks'][state['task_index']]
    rows = state['records']
    i = len(rows)
    rng = random.Random(f"{state['seed']}:{task}:{i}")
    adaptive = state['adaptive']
    public = {'task': TASKS[task], 'instructions': RULES[task], 'trial': i + 1}
    private = {}
    if task == 'traits':
        order = list(range(1, len(QUESTION_TEXT) + 1))
        random.Random(state['seed']).shuffle(order)
        number = order[i]
        private['question_id'] = f'q{number:03d}'
        public.update(text=QUESTION_TEXT[number - 1], allowed_actions=[1, 2, 3, 4, 5, None],
                      deadline_ms=rng.randint(6000, 8000))
    elif task in ('radar-control', 'emergency-brake'):
        stages = [False] * (59 if task == 'radar-control' else 52)
        stages += [True] * (LENGTHS[task] - len(stages))
        random.Random(state['seed']).shuffle(stages)
        stop = stages[i]
        private['stop'] = stop
        public.update(allowed_actions=['space', None])
        if task == 'radar-control':
            public.update(stimulus='빨강 위험 비행체' if stop else '초록 일반 비행체',
                          deadline_ms=adaptive.get('duration', 700))
        else:
            private['ssd_ms'] = adaptive.get('ssd', 250)
            public.update(stimulus=[{'at_ms': 0, 'color': 'green'}] + (
                [{'at_ms': private['ssd_ms'], 'color': 'red'}] if stop else []), deadline_ms=1000)
        private['correct_action'] = None if stop else 'space'
    elif task == 'sorting-center':
        rule = rng.choice(['color', 'shape'])
        color, shape = rng.randrange(2), rng.randrange(2)
        previous = rows[-1]['observation']['rule'] if rows else None
        private.update(is_switch=previous is not None and previous != rule,
                       correct_action=['left', 'right'][color if rule == 'color' else shape])
        public.update(rule=rule, color=['파랑', '노랑'][color], shape=['원', '네모'][shape],
                      allowed_actions=['left', 'right', None], deadline_ms=adaptive.get('duration', 1500))
    elif task == 'space-station-schedule':
        event_rng = random.Random(state['seed'])
        event_indices = [event_rng.randrange(20, 50), event_rng.randrange(70, 110)]
        symbol = '★' if i in event_indices else rng.randint(1, 9)
        private['correct_action'] = 'p' if symbol == '★' else ('right' if symbol % 2 == 0 else 'left')
        public.update(symbol=symbol, elapsed_ms=i * 1900, allowed_actions=['left', 'right', 'p'],
                      action_format='0~2개의 서로 다른 행동 배열', deadline_ms=1500)
    elif task == 'quality-inspector':
        size = rng.choice([10, 20, 30, 40])
        pieces = ['blue'] * size
        if rng.random() < .5:
            pieces[rng.randrange(size)] = 'yellow_rotated'
        private.update(has_target='yellow_rotated' in pieces,
                       correct_action='f' if 'yellow_rotated' in pieces else 'j')
        public.update(pieces=pieces, allowed_actions=['f', 'j', None], deadline_ms=4000)
    elif task == 'cipher-lab':
        tier = adaptive.get('tier', 1)
        attrs = ['rotation', 'count', 'size']
        active = rng.sample(attrs, 2 if tier == 3 else 1)
        base = dict(rotation=0, count=2, size=36)
        steps = dict(rotation=30 if tier == 2 else 90, count=1, size=8 if tier == 2 else 20)

        def panel(k):
            p = {a: base[a] + (k * steps[a] if a in active else 0) for a in attrs}
            p.update(rotation=p['rotation'] % 360, count=min(6, p['count']), size=min(90, p['size']))
            return p

        wrong = panel(2)
        inactive = next(a for a in attrs if a not in active)
        wrong[inactive] = base[inactive] + steps[inactive]
        options = [panel(3), panel(5), panel(1), wrong]
        rng.shuffle(options)
        private.update(correct_action=options.index(panel(3)), tier=tier)
        public.update(panels=[panel(k) for k in range(3)], options=options, allowed_actions=[0, 1, 2, 3, None])
    elif task == 'flash-comm':
        color, shape = rng.choice(['blue', 'orange']), rng.choice(['circle', 'square'])
        lag = [1, 2, 3, 5, 8][i % 5]
        private.update(correct_action=[color, shape], lag=lag)
        public.update(sequence=['gray'] * rng.randint(4, 6) + [color + '_circle']
                      + ['gray'] * (lag - 1) + ['black_' + shape] + ['gray'] * 3,
                      frame_ms=140 if i < 10 else 110,
                      allowed_actions=[['blue', 'orange'], ['circle', 'square']], action_format='색, 모양 순서의 배열')
    elif task == 'drone-tracking':
        n = adaptive.get('targets', 2)
        objects = [(rng.uniform(16, 624), rng.uniform(16, 344), rng.uniform(0, 2 * math.pi)) for _ in range(10)]
        targets = rng.sample(range(10), n)
        frames = []
        last_order = []
        for frame in range(13):
            positions = []
            for idx, (x, y, angle) in enumerate(objects):
                # Reflected constant-speed paths; anonymous spatial samples, not DOM identities.
                px = 16 + 608 - abs((x - 16 + 90 * math.cos(angle) * frame / 2) % 1216 - 608)
                py = 16 + 328 - abs((y - 16 + 90 * math.sin(angle) * frame / 2) % 656 - 328)
                positions.append((round(px, 1), round(py, 1), idx))
            positions.sort()
            last_order = [p[2] for p in positions]
            frames.append({'at_ms': frame * 500, 'positions': [[p[0], p[1]] for p in positions]})
            if frame == 0:
                frames[-1]['highlighted'] = [j for j, p in enumerate(positions) if p[2] in targets]
        private.update(correct_action=[j for j, idx in enumerate(last_order) if idx in targets], targets=n)
        public.update(frames=frames, allowed_actions=list(range(10)), action_format=f'서로 다른 번호 {n}개의 배열')
    elif task == 'expedition-investment':
        public.update(allowed_actions=list(EXPEDITION_BASE_DECKS),
                      running_total=sum(r['outcome']['amount'] for r in rows))
    return public, private


def validate_action(task, action, public, private):
    if task in ('space-station-schedule', 'drone-tracking', 'flash-comm'):
        if not isinstance(action, list):
            return False
        if task == 'flash-comm':
            return len(action) == 2 and all(type(v) is str and v in public['allowed_actions'][j] for j, v in enumerate(action))
        if task == 'drone-tracking':
            return (len(action) == private['targets'] and all(type(v) is int and 0 <= v < 10 for v in action)
                    and len(set(action)) == len(action))
        return (len(action) <= 2 and all(type(v) is str and v in public['allowed_actions'] for v in action)
                and len(set(action)) == len(action))
    return any(type(action) is type(v) and action == v for v in public['allowed_actions'])


def advance(state):
    task = state['tasks'][state['task_index']]
    public, private = observation(state)
    # Only visible past choices/outcomes reach the model, never scoring keys or future payoffs.
    history = [{'observation': r['observation'], 'action': r['action'],
                **({'feedback': {'amount': r['outcome']['amount']}} if task == 'expedition-investment' else {})}
               for r in state['records'][-10:]]
    result = decide(state['model'], state['persona'], public, history, state['id'])
    action = result['action']
    if not validate_action(task, action, public, private):
        raise SimulationError('LLM이 허용되지 않은 행동을 반환했습니다. 같은 단계에서 재시도하세요.')
    rt = result['simulated_rt_ms']
    timed_out = 'deadline_ms' in public and rt >= public['deadline_ms']
    effective = ([] if task == 'space-station-schedule' else None) if timed_out else action
    outcome = {'timed_out': timed_out}
    adaptive = state['adaptive']
    index = len(state['records'])
    if task == 'traits':
        outcome.update(question_id=private['question_id'], value=effective,
                       timed_out=effective is None, rt_ms=min(rt, public['deadline_ms']) if effective is not None else public['deadline_ms'])
    elif task == 'expedition-investment':
        source = EXPEDITION_REVERSAL_MAP[action] if index >= EXPEDITION_REVERSAL_INDEX else action
        deck = EXPEDITION_BASE_DECKS[source]
        loss = random.Random(f"{state['seed']}:payoff:{index}").random() < deck['loss_prob']
        amount = deck['win_amt'] - (deck['loss_amt'] if loss else 0)
        outcome.update(amount=amount, is_loss=loss,
                       running_total=public['running_total'] + amount)
    elif task == 'space-station-schedule':
        outcome['correct'] = private['correct_action'] in effective
        now = public['elapsed_ms'] + min(rt, public['deadline_ms'])
        hits = adaptive.setdefault('time_hits', [])
        if 'p' in effective and public['symbol'] != '★':
            target = next((t for t in (80000, 160000) if t <= now <= t + 15000 and t not in hits), None)
            if target is not None:
                hits.append(target)
                outcome['time_promise'] = target
            else:
                outcome['premature_p'] = True
    elif task == 'drone-tracking':
        accuracy = len(set(effective) & set(private['correct_action'])) / private['targets']
        outcome.update(correct=accuracy == 1, tracking_accuracy=accuracy, n_targets=private['targets'])
        streak = adaptive.get('streak', 0) + 1 if accuracy == 1 else 0
        if streak >= 2:
            adaptive['targets'], streak = min(5, private['targets'] + 1), 0
        elif accuracy < .5:
            adaptive['targets'] = max(2, private['targets'] - 1)
        adaptive['streak'] = streak
    else:
        correct = effective == private['correct_action']
        outcome.update(correct=correct)
        if task == 'flash-comm':
            outcome.update(t1_correct=effective[0] == private['correct_action'][0],
                           t2_correct=effective[1] == private['correct_action'][1], lag=private['lag'])
        if task == 'sorting-center':
            outcome['is_switch'] = private['is_switch']
        if task == 'emergency-brake' and private['stop']:
            adaptive['ssd'] = max(50, min(900, private['ssd_ms'] + (50 if correct else -50)))
        if task in ('radar-control', 'sorting-center'):
            recent = [r['outcome']['correct'] for r in state['records'][-9:]] + [correct]
            if len(recent) == 10:
                lo, hi, step = (400, 900, 50) if task == 'radar-control' else (700, 2000, 100)
                change = -step if mean(recent) >= .9 else step if mean(recent) < .7 else 0
                adaptive['duration'] = max(lo, min(hi, public['deadline_ms'] + change))
        if task == 'cipher-lab':
            tier = private['tier']
            streak = adaptive.get('streak', 0) + 1 if correct else 0
            if not correct:
                tier = max(1, tier - 1)
            elif streak >= 2:
                tier, streak = min(3, tier + 1), 0
            adaptive.update(tier=tier, streak=streak)
    row = {'seq': index, 'observation': public, **result, 'effective_action': effective, 'outcome': outcome}
    state['records'].append(row)
    completed = None
    if len(state['records']) >= state['limits'][task]:
        completed = {'task': task, 'title': TASKS[task], 'summary': summarize(task, state['records'], adaptive),
                     'records': state['records']}
        # Completed raw logs stay in the browser export; signed state only needs the active task.
        state['completed'].append({k: v for k, v in completed.items() if k != 'records'})
        state['task_index'] += 1
        state['records'] = []
        state['adaptive'] = {}
    return row, completed


def summarize(task, rows, adaptive):
    result = {
        'n_trials': len(rows), 'protocol_trials': LENGTHS[task],
        'complete_protocol': len(rows) == LENGTHS[task],
        'mean_simulated_rt_ms': round(mean(r['simulated_rt_ms'] for r in rows), 1),
        'mean_llm_latency_ms': round(mean(r['llm_latency_ms'] for r in rows), 1),
        'timing_source': 'LLM이 생성한 가상 시간. 사람의 측정값이 아님.',
    }
    if task == 'traits':
        answers = {r['outcome']['question_id']: {
            'value': r['outcome']['value'], 'rt_ms': r['outcome']['rt_ms'],
            'timed_out': r['outcome']['timed_out'], 'seq': r['seq'],
        } for r in rows}
        result.update(domain_scores=score_answers(answers), response_quality=response_quality(answers))
    elif task == 'expedition-investment':
        after_loss = [(a, b) for a, b in zip(rows, rows[1:]) if a['outcome']['is_loss']]
        result.update(final_total=sum(r['outcome']['amount'] for r in rows),
                      loss_stay_rate=mean(a['action'] == b['action'] for a, b in after_loss) if after_loss else None,
                      first_half_choices=[r['action'] for r in rows[:EXPEDITION_REVERSAL_INDEX]],
                      second_half_choices=[r['action'] for r in rows[EXPEDITION_REVERSAL_INDEX:]])
    else:
        result['accuracy'] = round(mean(r['outcome']['correct'] for r in rows), 4)
        if task == 'space-station-schedule':
            result['time_promise_hits'] = len(adaptive.get('time_hits', []))
            result['time_promises_reached'] = sum(t <= (len(rows) - 1) * 1900 + 1500 for t in (80000, 160000))
        if task == 'drone-tracking':
            result['tracking_accuracy'] = mean(r['outcome']['tracking_accuracy'] for r in rows)
        if task == 'flash-comm':
            result.update(t1_accuracy=mean(r['outcome']['t1_correct'] for r in rows),
                          t2_accuracy=mean(r['outcome']['t2_correct'] for r in rows))
    return result
