# Generated by Django 5.2.15 on 2026-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_email', models.EmailField(max_length=254)),
                ('question', models.CharField(default='1분 동안 자기소개를 해주세요.', max_length=300)),
                ('transcript', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='interviews/')),
                ('follow_up_question', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
