# Generated by Django 5.2.15 on 2026-08-16 15:03

import django.db.models.deletion
import interviews.models
from django.db import migrations, models


def link_candidates(apps, schema_editor):
    Candidate = apps.get_model('invites', 'Candidate')
    InterviewResponse = apps.get_model('interviews', 'InterviewResponse')
    for response in InterviewResponse.objects.filter(candidate__isnull=True).iterator():
        candidate = Candidate.objects.filter(email=response.respondent_email).order_by('-created_at', '-pk').first()
        if candidate:
            response.candidate_id = candidate.pk
            response.save(update_fields=['candidate'])


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_responses', to='invites.candidate'),
        ),
        migrations.RunPython(link_candidates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='interviewresponse',
            name='video',
            field=models.FileField(upload_to=interviews.models.interview_upload_to),
        ),
    ]
