# Generated by Django 5.2.15 on 2026-08-16 15:05

import interviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewresponse_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='follow_up_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='follow_up_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='follow_up_video',
            field=models.FileField(blank=True, upload_to=interviews.models.interview_upload_to),
        ),
    ]
