# Generated by Django 5.2.15 on 2026-08-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.SlugField(default='go-nogo')),
                ('respondent_email', models.EmailField(max_length=254)),
                ('trials', models.JSONField()),
                ('summary', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
