# Generated by Django 5.2.15 on 2026-08-16 15:03

import django.db.models.deletion
from django.db import migrations, models


def link_candidates(apps, schema_editor):
    Candidate = apps.get_model('invites', 'Candidate')
    GameResult = apps.get_model('games', 'GameResult')
    for result in GameResult.objects.filter(candidate__isnull=True).iterator():
        candidate = Candidate.objects.filter(email=result.respondent_email).order_by('-created_at', '-pk').first()
        if candidate:
            result.candidate_id = candidate.pk
            result.save(update_fields=['candidate'])


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='invites.candidate'),
        ),
        migrations.RunPython(link_candidates, migrations.RunPython.noop),
    ]
